name: Run Selenoid / Selenium Grid Extension Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Run all chrome tests
        run: make test

      - name: Run firefox selenoid tests
        run: make testSelenoidFirefox

      - name: Run firefox selenium grid tests
        run: make testSeleniumFirefox

      - uses: actions/upload-artifact@v2
        with:
         name: used_infrastructure
         path: ./src/test/resources/*compose.yaml
